awslabs/sensitive-data-protection-on-aws

.github/workflows/gh-pages.yml, buildspec.yml, source/constructs/api/main.py, source/constructs/lib/admin/database/whole/99_version.sql, source/constructs/lib/admin/glue-stack.ts, source/constructs/lib/agent/delete-agent-resources/delete_agent_resources.py, source/portal/src/pages/add-account/types/add_account_type.ts
Current version is 0.10.0
Change version to 1.0.0.
**Checklist
=> fix(others): Change Version

docs/en/architecture-overview/design-considerations.md
=> chore: update doc for cloudwatch alarms

source/portal/src/pages/data-job/index.tsx, source/portal/src/pages/data-source-connection/componments/DataSourceList.tsx, source/portal/src/pages/template-delete/index.tsx, source/portal/src/pages/template-identifiers/tables/IdentifierTable.tsx
1.  job page did not refresh after execute actions
2. delete identifier with alert information
3. sync to catalog set selected item to empty after refresh button
**Checklist
=> fix(fe): fix ui bugs

docs/en/architecture-overview/design-considerations.md, docs/en/security.md
=> docs: update security document

docs/en/security.md
=> docs: update security doc

.github/pull_request_template.md, CONTRIBUTING.md
=> chore: update PR template

source/constructs/api/db/models_catalog.py
=> fix(be): add search column for catalog table

docs/zh/architecture-overview/architecture-details.md
=> doc: add cn doc

source/constructs/api/discovery_job/service.py
Athena only supports 1000 results.
more than 1000
**Checklist
=> fix(be): athena result more than 1000

source/portal/public/locales/en/account.json, source/portal/public/locales/en/common.json, source/portal/public/locales/en/info.json, source/portal/public/locales/zh/account.json, source/portal/public/locales/zh/common.json, source/portal/public/locales/zh/info.json, source/portal/src/common/HelpInfo.tsx, source/portal/src/common/external-link-group.tsx, source/portal/src/common/separated-list/index.tsx, source/portal/src/common/separated-list/styles.module.scss, source/portal/src/i18n.ts, source/portal/src/pages/account-management/index.tsx, source/portal/src/pages/add-account/componments/AddAccountInfo.tsx, source/portal/src/pages/add-account/index.tsx, source/portal/src/pages/add-account/types/add_account_type.ts, source/portal/src/pages/create-identifier/index.tsx, source/portal/src/pages/create-job/index.tsx, source/portal/src/pages/data-catalog/componments/CatalogDetailList.tsx, source/portal/src/pages/data-catalog/index.tsx, source/portal/src/pages/data-job/index.tsx, source/portal/src/pages/data-source-connection/index.tsx, source/portal/src/pages/data-template/index.tsx, source/portal/src/pages/glue-job/index.tsx, source/portal/src/pages/resources-filter/index.tsx, source/portal/src/pages/summary/index.tsx, source/portal/src/pages/template-identifiers/index.tsx, source/portal/src/ts/common.ts
=> fix(fe): add page help info and fix issues

docs/en/deployment/deployment.md, docs/zh/deployment/deployment.md
=> docs(others): added notes in deployment

README.md
=> chore(others): update README.md

source/constructs/api/data_source/s3_detector.py, source/constructs/api/data_source/service.py, source/constructs/api/logging.conf
Only obtain private subnets.
Supporting public network subnets with glue endpoint and s3 endpoint.
**Checklist
=> feat(be): Modify Check Subnet Rules

source/constructs/api/catalog/service.py
=> fix(be): optimize catalog sync detection job

source/constructs/config/job/script/glue-job.py
The code generates a new column for each pair of column & identifier before summarizing detection results.
The code now only reads the output column from result of the Glue detection output dataframe.
Add comments for the functions for readability.
**Checklist
- [ * ] I have tested my changes.
- [ * ] No sensitive information is included.
- [ * ] I've reviewed my changes to ensure they won't cause any new issues that could affect the stability or performance of the codebase.
- [ * ] I confirm this changes has been test with [authorization validation …
=> fix(be): Optimize glue detection

source/constructs/api/catalog/crud.py, source/constructs/api/catalog/service.py
=> fix(be): optimize code

source/constructs/api/common/constant.py, source/constructs/api/common/enum.py, source/constructs/api/discovery_job/main.py, source/constructs/api/discovery_job/schemas.py, source/constructs/api/discovery_job/service.py, source/constructs/lib/admin/api-stack.ts, source/constructs/lib/admin/database/whole/10_discovery_job.sql, source/portal/src/apis/data-job/api.ts, source/portal/src/pages/glue-job/index.tsx
Get progress separately for each database.
Unified progress for a job run.
**Checklist
=> fix(be): get_run_progress

docs/en/user-guide/data-catalog-create.md, docs/zh/user-guide/data-catalog-create.md
=> docs(others): update rds permissions prerequisite.

source/constructs/api/db/models_version.py, source/constructs/api/main.py, source/constructs/api/version/crud.py, source/constructs/api/version/main.py, source/constructs/api/version/service.py
=> feat(be): Add api for version info

source/constructs/api/data_source/service.py
=> fix(be): modify the rules for obtaining subnet.

source/constructs/api/requirements.txt, source/constructs/api/template/crud.py, source/portal/src/App.tsx, source/portal/src/pages/signed-in-page/LayoutHeader.tsx, source/portal/src/ts/common.ts
=> feat(be): Update logic of version and batch insert identity-mappings

source/constructs/api/README.md, source/constructs/lib/admin/alb-stack.ts
=> fix(others): add version for the config api.

source/portal/src/pages/create-job/index.tsx
Support set time slot for job
**Checklist
=> feat(fe): on-schedule job with specific time slot

source/portal/src/pages/create-job/index.tsx
=> feat(fe): on-schedule job with specific time slot add timezone

source/portal/public/locales/en/job.json, source/portal/src/pages/create-job/index.tsx, source/portal/src/pages/data-catalog/types/data_config.ts
=> fix(fe): add sort for RDS tables list

source/constructs/api/catalog/crud.py, source/constructs/api/catalog/main.py, source/constructs/api/catalog/service_dashboard.py
=> fix(be): add view catalog by table interface

source/constructs/config/job/script/glue-job.py
Add Postprocessing for Glue EntityDetector in Job
Now only columns with names that meet specific rules will be identified as PERSON_NAME.
**Checklist
=> feat(be): Add Postprocessing for Glue EntityDetector in Job

source/constructs/config/job/script/glue-job.py
=> feat(be): Adapt empty or non-existing template in Glue Job

buildspec.yml
=> fix(fe): Update nodejs

buildspec.yml
=> fix(be): fix build error

source/portal/src/App.tsx, source/portal/src/pages/signed-in-page/LayoutHeader.tsx, source/portal/src/ts/types.ts
=> fix(fe): ui cognito logout issue

source/portal/src/index.scss, source/portal/src/pages/common-badge/index.tsx, source/portal/src/pages/common-badge/style.scss, source/portal/src/pages/data-catalog/componments/CatalogDetailList.tsx, source/portal/src/pages/glue-job/index.tsx, source/portal/src/pages/signed-in-page/LayoutHeader.tsx
=> fix(fe): ui bug fix

deployment/build-s3-dist.sh, source/constructs/api/lambda/portal_config.py, source/constructs/lib/admin-stack.ts, source/constructs/lib/admin/alb-stack.ts, source/constructs/lib/admin/cognito-post-stack.ts, source/constructs/lib/admin/cognito-post/cognito-post.py, source/constructs/lib/admin/cognito-stack.ts, source/constructs/lib/agent-stack.ts, source/constructs/lib/agent/DiscoveryJob.json
=> fix(others): Add agent version

source/constructs/api/catalog/service.py, source/portal/public/locales/zh/job.json, source/portal/src/pages/data-source-connection/componments/DataSourceList.tsx
=> fix(be): rds dialog error

buildspec.yml, source/constructs/api/db/models_discovery_job.py, source/constructs/api/discovery_job/schemas.py, source/constructs/api/discovery_job/service.py, source/constructs/lib/admin/database/1.0.1-1.0.2/20_update.sql, source/constructs/lib/admin/database/1.0.1-1.0.2/99_version.sql, source/constructs/lib/admin/database/init_db.py, source/constructs/lib/admin/database/whole/99_version.sql, source/portal/src/pages/glue-job/index.tsx
=> fix(others): Unable to display error log

source/constructs/lib/admin-stack.ts, source/constructs/lib/agent-stack.ts
=> feat(be): integrate agent to admin stack

source/constructs/api/catalog/service.py, source/constructs/api/lambda/crawler_event.py, source/constructs/api/lambda/sync_crawler_results.py
=> feat(be): sync catalogs

source/constructs/api/catalog/service.py, source/constructs/api/common/enum.py, source/constructs/api/lambda/sync_crawler_results.py
=> fix(be): unify the jdbc and provider

source/constructs/api/lambda/crawler_event.py, source/constructs/api/lambda/sync_crawler_results.py
=> fix(be): add glue database type

buildspec.yml, source/constructs/lib/admin-stack.ts
=> fix(be): deployment error for pipeline

source/constructs/lib/agent/unstructured-crawler/UnstructuredCrawler.py
=> feat(be): Fix unstructured crawler to avoid detecting folders

source/constructs/api/catalog/crud.py, source/constructs/api/catalog/service.py, source/constructs/api/common/enum.py, source/constructs/api/lambda/crawler_event.py, source/constructs/api/lambda/sync_crawler_results.py, source/constructs/lib/agent/delete-agent-resources/delete_agent_resources.py, source/portal/src/enum/common_types.ts
=> fix(be): fix crawler and database resources name

source/constructs/api/catalog/service.py, source/constructs/api/data_source/crud.py, source/constructs/api/data_source/main.py, source/constructs/api/data_source/service.py, source/portal/src/apis/data-source/api.ts, source/portal/src/pages/data-source-connection/componments/DataSourceList.tsx
=> feat(be): delete data source and catalog

source/constructs/api/data_source/main.py
=> fix(be): delete data source and catalog

source/portal/package-lock.json, source/portal/package.json
=> chore(fe): update postcss

.github/workflows/pull-request-check.yaml
=> fix(be): update pull-request-check.yaml

.github/workflows/pull-request-check.yaml
=> fix(be): fix workflow

source/constructs/api/catalog/service.py, source/constructs/api/common/enum.py, source/constructs/api/lambda/sync_crawler_results.py
=> feat(be): fix dashboard

source/constructs/lib/agent/DiscoveryJob-stack.ts
=> fix(others): delete sfn log

source/portal/package-lock.json, source/portal/package.json
=> fix(fe): upgrade @babel/traverse to 7.23.2

source/constructs/api/data_source/service.py, source/portal/src/pages/account-management/componments/AccountList.tsx, source/portal/src/pages/add-account/componments/AddAccountInfo.tsx
=> fix(fe): reslove aws account

source/constructs/api/data_source/crud.py, source/constructs/api/data_source/glue_database_detector.py, source/constructs/api/data_source/rds_detector.py, source/constructs/api/data_source/schemas.py, source/constructs/api/data_source/service.py, source/portal/src/apis/data-source/api.ts, source/portal/src/pages/data-source-connection/componments/DataSourceList.tsx, source/portal/src/pages/data-source-connection/componments/JDBCConnectionEdit.tsx
=> feat(be+fe): Update for glue database

source/constructs/lib/admin-stack.ts, source/constructs/lib/admin/acm-stack.ts, source/constructs/lib/admin/alb-stack.ts, source/constructs/lib/admin/api-stack.ts, source/constructs/lib/admin/call-region-stack.ts, source/constructs/lib/admin/cognito-post-stack.ts, source/constructs/lib/admin/delete-resources-stack.ts, source/constructs/lib/admin/glue-stack.ts, source/constructs/lib/admin/rds-stack.ts, source/constructs/lib/agent-stack.ts, source/constructs/lib/agent/DeleteAgentResources-stack.ts, source/constructs/lib/agent/DiscoveryJob-stack.ts, source/constructs/lib/agent/RenameResources-stack.ts, source/constructs/lib/common/build-config.ts
=> feat(cdk): Temporarily delete AgentRole

source/constructs/api/discovery_job/service.py, source/constructs/lib/agent-stack.ts
=> feat(cdk): Temporarily delete AgentRole_Job

source/constructs/api/common/enum.py, source/constructs/api/data_source/crud.py, source/constructs/api/data_source/service.py, source/portal/public/locales/en/common.json, source/portal/src/pages/data-source-connection/componments/DataSourceList.tsx, source/portal/src/pages/data-source-connection/types/data_config.ts
Glue database sync state is not correct
Fix this issue
**Checklist
=> fix(be): sync glue state

source/constructs/lib/agent-stack.ts, source/constructs/lib/agent/DiscoveryJob.json, source/constructs/lib/agent/split-job/split_job.py
=> feat(cdk): Recover agent

source/constructs/lib/agent/unstructured-crawler/UnstructuredCrawler.py
=> fix(be): unstructured incremental scan

source/constructs/api/catalog/service_dashboard.py
=> fix(be): add more jdbc type in dashboard

source/constructs/api/catalog/service.py, source/constructs/api/data_source/crud.py, source/constructs/api/data_source/schemas.py, source/constructs/api/data_source/service.py, source/constructs/api/db/database.py, source/constructs/api/lambda/sync_crawler_results.py, source/portal/src/pages/data-source-connection/componments/DataSourceList.tsx
=> feat(be): sync JDBC Upgrade

source/constructs/api/data_source/crud.py, source/constructs/api/lambda/sync_crawler_results.py
=> feat(be): update catalog msg content

source/portal/src/enum/common_types.ts, source/portal/src/pages/create-job/components/SelectGlueCatalog.tsx, source/portal/src/pages/create-job/components/SelectJDBCCatalog.tsx, source/portal/src/pages/create-job/components/SelectRDSCatalog.tsx, source/portal/src/pages/create-job/index.tsx, source/portal/src/pages/data-job/index.tsx, source/portal/src/pages/data-job/types/job_list_type.ts
=> fix(fe): create job issues

source/constructs/api/catalog/service_dashboard.py, source/constructs/api/data_source/crud.py, source/constructs/api/data_source/jdbc_detector.py, source/portal/public/locales/en/account.json, source/portal/public/locales/zh/account.json, source/portal/src/pages/account-management/componments/AccountList.tsx, source/portal/src/pages/account-management/types/account_type.ts
=> feat(be+fe): add some columns in Datasource Table

source/constructs/lib/agent/unstructured-crawler/UnstructuredCrawler.py
=> fix(be): Unstructured Crawler Using BaseTime

source/constructs/api/discovery_job/crud.py, source/constructs/api/discovery_job/schemas.py, source/constructs/lib/admin/glue-stack.ts, source/constructs/lib/agent/DiscoveryJob.json
=> feat(cdk): Unstructured data BaseTime

source/portal/src/pages/create-job/components/SelectProvider.tsx, source/portal/src/pages/data-catalog/componments/DetailModal.tsx
=> fix(fe): fix ui issues

source/constructs/lib/admin/glue-stack.ts
=> fix(cdk): module version

source/constructs/package.json
=> chore(be): update cdk version

source/constructs/api/data_source/crud.py, source/constructs/api/data_source/jdbc_detector.py, source/constructs/api/template/crud.py, source/constructs/api/template/service.py, source/portal/src/pages/data-source-connection/componments/DataSourceList.tsx
=> fix(be): update data coverage code

source/constructs/package.json
=> fix(cdk): update cdk version

.github/workflows/pull-request-check.yaml, source/constructs/api/common/constant.py, source/constructs/lib/admin/database/init_db.py
=> fix(cdk): update sql

source/.viperlightignore, source/constructs/api/pytest/test_data_source.py, source/constructs/api/requirements.txt, source/constructs/package.json
=> test(be): add test case for data source api

source/constructs/api/lambda/auto_sync_data.py, source/constructs/api/main.py, source/constructs/lib/admin/alb-stack.ts, source/constructs/lib/admin/database/1.0.x-1.1.0/20_update.sql, source/constructs/lib/agent/RenameResources-stack.ts, source/constructs/lib/agent/rename-resources/rename_resources.py
=> fix(cdk): Upgrade 10x to 11x

source/constructs/api/data_source/service.py, source/constructs/lib/admin/database/1.0.x-1.1.0/20_update.sql, source/constructs/lib/agent/rename-resources/rename_resources.py
=> fix(cdk): rename connection

source/.viperlightignore, source/constructs/api/data_source/crud.py, source/constructs/api/label/crud.py, source/constructs/api/pytest/test_data_source.py, source/constructs/api/pytest/test_labels.py
=> test(be): add test case for label APIs

source/constructs/api/discovery_job/service.py
=> fix(be): table_count_unstructured

source/constructs/api/data_source/service.py, source/constructs/lib/admin-stack.ts, source/constructs/lib/agent/rename-resources/rename_resources.py
=> fix(cdk): fault-tolerant when upgrade

source/constructs/api/catalog/service.py, source/constructs/api/data_source/crud.py, source/constructs/api/lambda/sync_crawler_results.py
=> fix(be): sync status update failed

source/portal/public/locales/en/common.json, source/portal/public/locales/zh/common.json, source/portal/src/apis/data-source/api.ts, source/portal/src/pages/data-source-connection/componments/DataSourceList.tsx
=> fix(fe): glue database name is blanket 

source/portal/src/pages/create-job/components/SelectS3Catalog.tsx, source/portal/src/pages/create-job/index.tsx, source/portal/src/pages/create-job/types/create_data_type.ts, source/portal/src/pages/data-job/types/job_list_type.ts
=> feat(fe): choose bucket on S3 Job creation

source/constructs/api/pytest/test_query.py
=> test(be): add test case for query APIs

source/constructs/api/catalog/crud.py, source/constructs/api/catalog/main.py, source/constructs/api/catalog/schemas.py, source/constructs/api/catalog/service.py, source/constructs/api/common/constant.py, source/constructs/api/common/query_condition.py, source/constructs/api/db/models_catalog.py, source/constructs/lib/admin/database/1.0.x-1.1.0/20_update.sql, source/constructs/lib/admin/database/whole/10_catalog.sql
=> fix(be): fix size key and obj count in s3 catalog

source/constructs/api/data_source/crud.py, source/constructs/api/data_source/glue_database_detector.py, source/constructs/api/data_source/service.py
=> feat(be): do not start crawler in data source

source/portal/src/pages/add-account/componments/AccountForm.tsx
=> fix(fe): account name is empty

source/constructs/api/catalog/schemas.py, source/constructs/api/catalog/service.py, source/constructs/api/common/constant.py, source/constructs/api/db/models_catalog.py, source/constructs/lib/admin/database/1.0.x-1.1.0/20_update.sql, source/constructs/lib/admin/database/whole/10_catalog.sql
=> fix(be): add glue properties

source/constructs/api/discovery_job/main.py
=> fix(be): Remove obsolete APIs

source/constructs/api/catalog/service.py, source/constructs/api/lambda/sync_crawler_results.py
=> fix(be): fixed sync glue database event

source/constructs/api/discovery_job/service.py
=> fix(be): count jdbc table

source/constructs/api/lambda/sync_crawler_results.py
=> fix(be): fix bugs

source/constructs/api/common/abilities.py, source/constructs/api/discovery_job/service.py
=> fix(be): need_change_account_id to common

source/constructs/api/common/constant.py, source/constructs/api/data_source/rds_detector.py, source/portal/public/locales/en/account.json, source/portal/src/pages/account-management/componments/AccountList.tsx
=> fix(fe): dynamic load account count

source/portal/src/pages/create-job/types/create_data_type.ts
=> fix(fe): missing JDBC instance name in job creation

source/constructs/api/common/enum.py, source/constructs/api/data_source/service.py
=> fix(fe): JDBC sync with no schema error

source/constructs/api/catalog/service.py, source/constructs/api/common/abilities.py, source/constructs/api/lambda/sync_crawler_results.py
=> fix(be): sync crawler result for third-party JDBC

source/constructs/api/common/enum.py, source/constructs/api/discovery_job/service.py, source/constructs/lib/agent/AgentRole-stack.ts, source/constructs/lib/agent/DiscoveryJob.json
=> fix(be): check agent version

source/constructs/api/data_source/service.py, source/portal/src/pages/data-source-connection/componments/JDBCConnection.tsx
=> fix(be): fixed JDBC creation failed

source/constructs/api/data_source/rds_detector.py
=> fix(be): RDS list does not refresh

source/constructs/api/data_source/service.py
=> fix(be): RDS connection

source/portal/src/pages/create-job/components/SelectS3Catalog.tsx
=> fix(fe): only list activate s3 buckets in job creation

source/constructs/api/common/constant.py, source/constructs/api/data_source/service.py
=> fix(be): excluded unstructured file extensions

source/constructs/api/catalog/crud.py, source/constructs/api/common/enum.py, source/constructs/api/discovery_job/crud.py, source/constructs/api/discovery_job/service.py
=> fix(be): Job database is empty

source/portal/src/pages/data-catalog/componments/CatalogList.tsx
=> fix(fe): format number in rds table view

source/constructs/api/lambda/sync_crawler_results.py
=> fix(be): avoid to set active state when table is empty

source/constructs/api/discovery_job/crud.py, source/constructs/lib/agent/DiscoveryJob.json, source/constructs/lib/agent/split-job/split_job.py
=> fix(cdk): remove unnecessary content

source/constructs/api/catalog/crud.py, source/constructs/api/catalog/main.py
=> fix(be): add catalog count interface

source/constructs/api/common/constant.py, source/constructs/api/data_source/rds_detector.py, source/constructs/api/data_source/service.py, source/portal/src/pages/data-catalog/componments/CatalogDetailList.tsx, source/portal/src/pages/data-catalog/componments/CatalogList.tsx, source/portal/src/pages/data-catalog/componments/SchemaModal.tsx, source/portal/src/pages/data-source-connection/componments/DataSourceList.tsx, source/portal/src/pages/signed-in-page/LayoutHeader.tsx, source/portal/src/ts/common.ts
=> fix(fe): cumulative fixes for frontend

source/constructs/api/catalog/crud.py
=> fix(be): fix dashboard catalog file type bugs

source/portal/src/pages/data-catalog/componments/CatalogDetailList.tsx, source/portal/src/pages/data-catalog/componments/CatalogList.tsx
=> fix(fe): fixed to add import

source/constructs/api/discovery_job/service.py, source/constructs/lib/agent/DiscoveryJob-stack.ts
=> fix(be): create job with connection

source/constructs/lib/admin/api-stack.ts
=> fix(cdk): update lambda memorySize

source/constructs/api/data_source/glue_database_detector.py, source/constructs/api/data_source/service.py, source/portal/src/pages/data-source-connection/componments/JDBCConnection.tsx
=> fix(be): update glue database limit and show more detail about network when create JDBC

source/portal/public/aws-exports.json, source/portal/src/pages/data-catalog/componments/CatalogList.tsx, source/portal/src/pages/data-catalog/types/data_config.ts, source/portal/src/ts/common.ts
=> fix(fe): fix rds table view issues

source/constructs/api/data_source/crud.py, source/constructs/api/data_source/s3_detector.py, source/portal/public/locales/en/summary.json, source/portal/public/locales/zh/summary.json, source/portal/src/pages/data-catalog/componments/CatalogDetailList.tsx, source/portal/src/pages/summary/comps/charts/AmazonGlue.tsx, source/portal/src/pages/summary/comps/charts/JDBC.tsx, source/portal/src/pages/summary/comps/charts/items/IdentifierTable.tsx, source/portal/src/ts/common.ts
=> fix(fe): cumulative portal fix

source/portal/src/pages/data-catalog/types/data_config.ts
=> fix(fe): catalog rds column count incorrect

source/portal/public/aws-exports.json, source/portal/src/pages/create-job/index.tsx, source/portal/src/pages/create-job/types/create_data_type.ts, source/portal/src/pages/data-catalog/types/data_config.ts, source/portal/src/tools/tools.tsx
=> fix(fe): optimize create job rds table view

source/constructs/api/data_source/schemas.py
=> fix(fe): use str for account

source/constructs/api/catalog/service.py
=> fix(be): fix sql

source/portal/src/pages/account-management/componments/AccountList.tsx
=> fix(fe): fix page error when there is no account

source/portal/src/pages/data-source-connection/componments/DataSourceList.tsx
=> fix(fe): remove test connection button

source/constructs/api/catalog/main.py, source/portal/src/apis/dashboard/api.ts, source/portal/src/apis/data-source/api.ts, source/portal/src/pages/data-source-connection/componments/DataSourceList.tsx
=> fix(fe): code cleanup, remove unused API

source/constructs/api/common/db_base_col.py
=> fix(be): Batch execution performance issue

source/constructs/api/catalog/crud.py, source/constructs/api/catalog/main.py, source/constructs/api/catalog/service.py
=> fix(be): fix catalog size and obj count

source/constructs/api/db/models_discovery_job.py, source/constructs/api/discovery_job/crud.py, source/constructs/api/discovery_job/schemas.py, source/constructs/api/discovery_job/service.py, source/constructs/lib/admin/database/1.0.x-1.1.0/20_update.sql, source/constructs/lib/admin/database/whole/10_discovery_job.sql, source/portal/src/pages/glue-job/index.tsx
=> fix(be): change error_log column to error_content

source/constructs/api/data_source/crud.py
=> fix(be): update coverage api

source/constructs/api/catalog/crud.py
=> feat(be): dashboard matrix bug fix about catalog

source/constructs/lib/agent/DiscoveryJob.json
=> fix(be): add crawler status condition

source/constructs/api/catalog/service.py
=> fix(be): fix catalog NA

source/portal/src/pages/create-job/index.tsx
=> fix(fe): correct database type in table view when creating jobs

.gitignore, source/constructs/api/common/constant.py, source/constructs/api/discovery_job/service.py, source/constructs/api/requirements.txt
=> fix(be): Successful tasks within 15 minutes are not repeated

source/portal/src/pages/summary/comps/charts/JDBC.tsx
=> fix(fe): add proxy database type

source/containers/document-pii-detection/parser_factory.py
=> fix(be): fix unsupported file types in unstructured parser

source/constructs/api/data_source/crud.py, source/constructs/api/data_source/schemas.py, source/constructs/api/data_source/service.py, source/constructs/api/db/models_data_source.py, source/portal/public/locales/en/datasource.json, source/portal/public/locales/zh/datasource.json, source/portal/src/pages/data-source-connection/componments/JDBCConnection.tsx, source/portal/src/pages/data-source-connection/componments/JDBCConnectionEdit.tsx
=> feat(be): support database name as a list in JDBC connection

source/constructs/api/data_source/service.py
=> fix(be): edit database names for JDBC connection

source/portal/src/pages/data-source-connection/componments/JDBCConnection.tsx, source/portal/src/pages/data-source-connection/componments/JDBCConnectionEdit.tsx
=> fix(fe): not to disable save

source/portal/src/pages/summary/comps/charts/items/JDBCCatalogOvervie.tsx
=> fix(fe): dashboard issue

source/portal/src/pages/data-source-connection/componments/JDBCConnection.tsx
=> fix(fe): create jdbc issue

source/constructs/api/catalog/service_dashboard.py, source/constructs/api/data_source/crud.py
=> fix(be): avoid too long logs output

source/constructs/api/data_source/service.py, source/portal/src/pages/data-source-connection/componments/JDBCConnection.tsx, source/portal/src/pages/data-source-connection/componments/JDBCConnectionEdit.tsx
=> fix(fe): connection validate when create jdbc

source/portal/public/locales/en/datasource.json, source/portal/public/locales/zh/datasource.json, source/portal/src/apis/data-source/api.ts, source/portal/src/pages/data-source-connection/componments/JDBCConnection.tsx
=> fix(fe): find databases for JDBC

source/portal/src/pages/create-job/components/SelectJDBCCatalog.tsx, source/portal/src/pages/create-job/components/SelectProvider.tsx
=> fix(fe): update job creation for jdbc proxy

source/constructs/api/common/constant.py, source/constructs/api/common/reference_parameter.py, source/constructs/api/data_source/service.py, source/constructs/api/discovery_job/service.py, source/constructs/api/main.py, source/constructs/api/template/service.py, source/constructs/lib/admin/acm-stack.ts, source/constructs/lib/admin/api-stack.ts, source/constructs/lib/admin/glue-stack.ts, source/constructs/lib/admin/glue/add_partition.py, source/constructs/lib/agent-stack.ts, source/constructs/lib/agent/AgentRole-stack.ts, source/constructs/lib/agent/DiscoveryJob-stack.ts, source/constructs/lib/agent/DiscoveryJob.json, source/constructs/lib/common/bucket-stack.ts
=> fix(be): Bucket name is randomly named

source/constructs/api/data_source/service.py, source/portal/public/locales/en/datasource.json, source/portal/public/locales/zh/datasource.json, source/portal/src/pages/data-source-connection/componments/JDBCConnection.tsx, source/portal/src/pages/data-source-connection/componments/JDBCConnectionEdit.tsx, source/portal/src/pages/right-modal/index.tsx, source/portal/src/ts/right-modal/types.ts
=> fix(fe): update for jdbc connection creation

source/portal/src/pages/signed-in-page/LayoutHeader.tsx, source/portal/src/tools/apiRequest.tsx, source/portal/src/ts/common.ts
=> fix(fe): add prod mode to hide high level errors in frontend

source/constructs/api/data_source/service.py
=> fix(be): jdbc schemas

source/portal/nginx-config/nginx.conf
=> fix(fe): update CSP headers

source/constructs/api/discovery_job/service.py
=> fix(be): fixed depth_unstructured

source/constructs/lib/admin/alb-stack.ts
=> fix(be): fix a typo

source/constructs/api/data_source/service.py, source/constructs/lib/agent/DiscoveryJob.json, source/portal/src/enum/common_types.ts, source/portal/src/pages/create-job/components/SelectJDBCCatalog.tsx
=>  fix(be): count of jdbc should include proxy type

source/portal/src/pages/create-job/components/SelectS3Catalog.tsx, source/portal/src/pages/create-job/types/create_data_type.ts, source/portal/src/pages/data-job/componments/JobCatalogs.tsx, source/portal/src/pages/data-job/index.tsx, source/portal/src/pages/data-job/types/job_list_type.ts, source/portal/src/pages/data-source-connection/componments/DataSourceCatalog.tsx, source/portal/src/pages/glue-job/componments/GlueJobCatalog.tsx, source/portal/src/pages/glue-job/index.tsx
=> fix(fe): fix uat ui issues

source/constructs/api/catalog/service.py
=> fix(be): fix dashboard jump

source/portal/src/pages/create-job/index.tsx, source/portal/src/pages/create-job/types/create_data_type.ts, source/portal/src/pages/data-catalog/types/data_config.ts
=> fix(fe): create s3 job issue

source/portal/src/pages/data-catalog/componments/CatalogList.tsx
=> fix(fe): list jdbc proxy databases and tables in catalog list

source/constructs/bin/main.ts, source/constructs/lib/agent/DiscoveryJob.json, source/constructs/package.json
=> fix(cdk): update cdk-nag

source/constructs/api/data_source/crud.py
=> fix(be): fix total count for jdbc in summary

source/constructs/lib/admin/alb-stack.ts
=> fix(cdk): Move portal out of VPC

source/constructs/api/catalog/service.py, source/constructs/api/common/concurrent_upload2s3.py, source/constructs/api/data_source/service.py, source/portal/src/enum/common_types.ts, source/portal/src/pages/data-source-connection/componments/DataSourceList.tsx
=> fix(be): resolve some bugs caused by proxy account

source/constructs/api/catalog/service.py
=> feat(be): fix delete tables not work when sync catalogs

source/constructs/lib/admin/alb-stack.ts
=> fix(cdk): recover portal in VPC

source/portal/src/pages/data-catalog/componments/CatalogDetailList.tsx, source/portal/src/pages/data-catalog/types/data_config.ts
=> fix(fe): update time not correct

source/constructs/lib/agent/unstructured-crawler/UnstructuredCrawler.py
=> fix(be): fix unstructured crawler to display correct number of objects

source/constructs/lib/agent/AgentRole-stack.ts
=> fix(cdk): update policy

source/constructs/api/data_source/service.py
=> fix(be): update s3 crawler when sync s3

source/portal/src/pages/data-catalog/componments/SchemaModal.tsx
=> fix(fe): fixed catalog page cannot open table tab

source/portal/src/pages/data-catalog/componments/CatalogDetailList.tsx
=> fix(fe): filter unsupport file types

source/constructs/lib/agent/unstructured-crawler/UnstructuredCrawler.py
=> fix(be): optimize display of unstructured part

source/portal/public/aws-exports.json, source/portal/src/pages/data-catalog/componments/CatalogDetailList.tsx
=> fix(fe): incorrect database type

docs/mkdocs.zh.yml
Docs (others): fixed one broken link
=> docs(others): fixed broken link

source/constructs/api/data_source/crud.py, source/constructs/api/data_source/service.py, source/portal/src/pages/create-job/index.tsx
=> fix(be): jdbc proxy datasource can not be counted into statistics

source/.viperlightignore, source/constructs/bin/main.ts, source/constructs/lib/admin-stack.ts, source/constructs/lib/admin/cognito-stack.ts, source/constructs/lib/common/solution-info.ts
=> feat(be): update CDK for workshop initial user

source/portal/public/locales/en/common.json, source/portal/public/locales/zh/common.json, source/portal/src/pages/data-job/componments/JobProperties.tsx
=> fix(fe): i18n job properties

buildspec.yml, source/constructs/lib/admin/alb-stack.ts, source/constructs/lib/admin/rds-stack.ts
=> fix(cdk): upgrade rds version

source/constructs/lib/admin/glue-stack.ts
=> fix(cdk): add batch create jdbc datasource template

docs/en/user-guide/data-catalog-create-jdbc-redshift.md, docs/en/user-guide/data-catalog-create-jdbc.md, docs/zh/user-guide/data-catalog-create-jdbc-redshift.md, docs/zh/user-guide/data-catalog-create-jdbc.md
=> docs(others): added permissions for show view

source/portal/package-lock.json, source/portal/package.json
=> chore(fe): update frontend dependency

source/portal/package-lock.json, source/portal/package.json
=> chore(fe): upgrade dependency

docs/en/user-guide/appendix-database-proxy.md, docs/zh/user-guide/appendix-database-proxy.md
=> docs(others): batch proxy data source creation

source/constructs/api/catalog/crud.py, source/constructs/api/catalog/service.py, source/constructs/api/common/enum.py, source/constructs/api/data_source/service.py, source/portal/src/pages/data-source-connection/componments/JDBCConnection.tsx, source/portal/src/pages/data-source-connection/componments/JDBCConnectionEdit.tsx
=> fix(be): reslove datalog row count is 0

source/containers/document-pii-detection/parsers/parser.py
=> fix(be): fix hard code region in parser
